global:
  scrape_interval: 1m
  scrape_timeout: 20s
  evaluation_interval: 2m
  external_labels:
    cluster: swarm
    monitor: codelab-monitor
    replica: "1"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
   - "cpu.yml"
   - "target_up.yml"
   - "site_up.yml"

scrape_configs:
- job_name: 'blackbox200'
  metrics_path: /probe
  params:
      module: [http_2xx]
  static_configs:
      - targets:
        - http://traefik.services.alin.be/ping
        - https://visualizer.services.alin.be/
        - https://helloworld.services.alin.be/
        - https://portainer.services.alin.be/
        - https://hello.services.alin.be/greeting
        - https://employer.services.alin.be/metrics
        - https://file.services.alin.be/
        - https://whoami.services.alin.be/
        - https://grafana.services.alin.be/login
        - https://api.services.alin.be/hello
        - https://api.services.alin.be/employer
        - https://apidashboard.services.alin.be
        - https://alertmanager.services.alin.be
        - https://blackbox.services.alin.be/
        - https://minio-exporter.services.alin.be
        - https://minio.serices.alin.be
  relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox.services.alin.be  # Blackbox exporter.

- job_name: 'blackbox401'
  metrics_path: /probe
  params:
      module: [http_4xx]
  static_configs:
      - targets:
        - https://documentation.services.alin.be    # Reverse proxy test
        - https://cadvisor.services.alin.be
  relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox.services.alin.be  # Blackbox exporter.

- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090

- job_name: node-exporter
  static_configs:
  - targets:
    - node-exporter:9100
  dns_sd_configs:
  - names:
    - tasks.node-exporter
    refresh_interval: 30s
    type: A
    port: 9100

- job_name: docker
  static_configs:
  - targets:
    - 192.168.1.65:9323

- job_name: minio
  static_configs:
  - targets:
    - minio-exporter.services.alin.be

- job_name: cadvisor
  static_configs:
  - targets:
    - cadvisor:8080
  dns_sd_configs:
  - names:
    - tasks.cadvisor
    refresh_interval: 30s
    type: A
    port: 8080
- job_name: traefik
  static_configs:
  - targets:
    - traefik.services.alin.be
  basic_auth:
    username: admin
    password: Azerty123
